### ISSUE TITLE
配置问题求解

### ISSUE THREAD

**Issue by 527593036** [aliyun/mongo-shake#101]
具体情况如下，求解：

 ./collector -conf=../conf/collector.conf
Conf.Options check failed: context storage type or address is invalid

数据传输情况：
mongodb replicaset  --> mongo-shake --> monogdb

配置文件,这一部分没理解，求解答：
context.storage = mongoshake
context.address = chkp_default
context.start_position = 2000-01-01T00:00:01Z

请问，官方能否出一套配置实列？

**Comment by vinllen** [comment]
https://github.com/aliyun/mongo-shake/wiki/FAQ#q-how-can-i-configure-checkpoint

**Comment by 527593036** [comment]
非常感谢，已经解决
