### ISSUE TITLE
MongoShake出现了同步数据不完整的情况，数据的数量对不上，然后oplog的日志的数据却能对上

### ISSUE THREAD

**Issue by AllenWod** [aliyun/mongo-shake#103]
![image](https://user-images.githubusercontent.com/22765507/51434974-0d049b80-1ca8-11e9-9bcd-8a8d1e41c355.png)
![Uploading image.png…]()

**Comment by vinllen** [comment]
信息太少了，给下运行日志，配置，认为同步有问题的库表结构，另外还有存在问题的oplog是否能找到。

**Comment by vinllen** [comment]
问题没有反馈，先进行关闭，如果后续还有问题请重新打开

**Comment by marknewmail** [comment]
你看看是不是replayer.go的bson.Unmarshal(raw, &oplogs[i])这一句反序列化失效，导致Timestamp没值，ack时回传不了timestamp,改成json.Unmarshal(raw, &oplogs[i])试试
