### ISSUE TITLE
开始同步的时间

### ISSUE THREAD

**Issue by xzshinan** [aliyun/mongo-shake#105]
我在源库新建了db 和 collection （testshinan.test-shinan）， 里面两条数据 A 和 B。 时间是 2019-01-25 17：00 左右。  
然后，我在目标库，testshinan.test-shinan 加了数据A. 算是我理解的首次全量同步。
然后把配置项的  filter.namespace.white = testshinan.test-shinan 以及  context.start_position = 2019-01-25T00:00:01Z

问题：
 进程起了好久，我的数据B，还没过去。  他是要轮询全部的oplog么？还是从 2019-01-25T00:00:01Z 这个时间点开始的？

或者说   context.start_position 这个时间 需要 和 oplog里的时间要一致

**Comment by xzshinan** [comment]
> “我在目标库，testshinan.test-shinan 加了数据A. 算是我理解的首次全量同步。”
> 这个描述是啥意思？
> 你是说源库写入数据，目标库没有同步？

不是的。mongoshake 不是 只同步增量数据 么？我就是先在目标库把数据A给写入。 然后 再起的 mongoshake进程。 希望把数据B 以及 以后 源库的 testshinan.test-shinan 数据都同步到 目标库的 testshinan.test-shinan

**Comment by vinllen** [comment]
这个时间戳是oplog产生的时间戳，你看看你的数据时间是不是对的上，机器时间确定25号吗？另外，这个时间好像是utc时区的

**Comment by xzshinan** [comment]
> 这个时间戳是oplog产生的时间戳，你看看你的数据时间是不是对的上，机器时间确定25号吗？另外，这个时间好像是utc时区的

机器时间确定是 25 号的。

context.start_position 的时间知道是 utc。

但是 context.start_position 我设定的时间不是 oplog里 某条记录的时间。这个需要么？我以为时间只要稍早一些就可以。或者说 我设为 2019-01-01T00:00:01Z 可以么

**Comment by vinllen** [comment]
但是 context.start_position 我设定的时间不是 oplog里 某条记录的时间。这个需要么？我以为时间只要稍早一些就可以。或者说 我设为 2019-01-01T00:00:01Z 可以么
------
这个不需要知道具体时间，早些就可以

另外我有一个疑问，shake拉oplog 是直接从 > context.start_position 的时间拉起的。还是全oplog拉取，过滤 < context.start_position 的时间
------
前者

**Comment by xzshinan** [comment]
非常感谢解答~
