### ISSUE TITLE
为什么不在mongo-shake中添加GID，而是修改了mongo的源码？

### ISSUE THREAD

**Issue by someorz** [aliyun/mongo-shake#114]
你好，有个疑问想请教下，为什么不通过在mongo-shake中修改oplog添加GID，而是修改了mongo的源码添加。

**Comment by vinllen** [comment]
gid是oplog自带的，用于同步时过滤，mongo-shake没办法添加

**Comment by someorz** [comment]
想明白了，如果A同步到B，mongo-shake中修改A的oplog添加GID，同步到B时，B生成的oplog无法保留GID，这样无法避免循环复制。
