### ISSUE TITLE
数据同步缓慢

### ISSUE THREAD

**Issue by blessmylove** [aliyun/mongo-shake#115]
源库 replica set
目标库  replica set （只配置了主节点）

|        logs_get/sec |       logs_repl/sec |    logs_success/sec |            lsn.time |        lsn_ack.time |       lsn_ckpt.time |            now.time |             replset |
|---------------------|---------------------|---------------------|---------------------|---------------------|---------------------|---------------------|---------------------|
|                   0 |                   0 |                   0 | 2019-03-05 08:33:01 | 2019-03-05 08:33:06 | 2019-03-05 08:08:29 | 2019-03-09 14:23:38 |       mgset-7217065 |
|---------------------|---------------------|---------------------|---------------------|---------------------|---------------------|---------------------|---------------------|
|                   0 |                   0 |                   0 | 2019-03-05 08:33:01 | 2019-03-05 08:33:06 | 2019-03-05 08:08:29 | 2019-03-09 14:23:39 |       mgset-7217065 |
|---------------------|---------------------|---------------------|---------------------|---------------------|---------------------|---------------------|---------------------|
|                   0 |                   0 |                   0 | 2019-03-05 08:33:01 | 2019-03-05 08:33:06 | 2019-03-05 08:08:29 | 2019-03-09 14:23:40 |       mgset-7217065 |
|---------------------|---------------------|---------------------|---------------------|---------------------|---------------------|---------------------|---------------------|
|                   0 |                   0 |                   0 | 2019-03-05 08:33:01 | 2019-03-05 08:33:06 | 2019-03-05 08:08:29 | 2019-03-09 14:23:41 |       mgset-7217065 |

**Comment by vinllen** [comment]
检查下目的库的写入情况，你发给我的worker 7是有数据堆着的，可能目的端写入失败了，捞日志给我看下。
```
[
    {
        "count": 4028,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "6664698386123326056",
        "last_unack": "6664698386123326056",
        "worker_id": 0
    },
    {
        "count": 4,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "6664696689611243563",
        "last_unack": "6664696689611243563",
        "worker_id": 1
    },
    {
        "count": 8059,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "6664698390418293210",
        "last_unack": "6664698390418293210",
        "worker_id": 2
    },
    {
        "count": 8,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "6664696689611243566",
        "last_unack": "6664696689611243566",
        "worker_id": 3
    },
    {
        "count": 548,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "6664698386123327106",
        "last_unack": "6664698386123327106",
        "worker_id": 4
    },
    {
        "count": 94,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "6664698373238426038",
        "last_unack": "6664698373238426038",
        "worker_id": 5
    },
    {
        "count": 190,
        "jobs_in_queue": 0,
        "jobs_unack_buffer": 0,
        "last_ack": "6664698364648491843",
        "last_unack": "6664698364648491843",
        "worker_id": 6
    },
    {
        "count": 22438,
        "jobs_in_queue": 64,
        "jobs_unack_buffer": 0,
        "last_ack": "6664692819845711889",
        "last_unack": "6664698390418293326",
        "worker_id": 7
    }
]
```

**Comment by vinllen** [comment]
把shake部署到离目的mongodb近一些可以解决这个问题，这是因为mgo库写性能导致的。
