### ISSUE TITLE
woker之间唯一索引冲突如何避免

### ISSUE THREAD

**Issue by a188616786a** [aliyun/mongo-shake#15]
代码中，batcher根据文档id或ns的hash值，将oplog发送给不同的woker，然后在woker内部检查冲突。但是如果是根据id进行hash，同一ns的oplog可能会发送到不同的woker，那么不同woker中会不会出现唯一索引冲突的情况？这种冲突可以检测到吗？

**Comment by vinllen** [comment]
如果存在唯一键，是按collection进行hash，不能按id哈希，配置模式为auto，mongoshake会自动识别。

**Comment by a188616786a** [comment]
明白了 多谢
