### ISSUE TITLE
Syncing with mongo 3.6 - bug

### ISSUE THREAD

**Issue by omerzamir** [aliyun/mongo-shake#16]
When trying to sync 3.6 mongodb, mongo-shake prints an error 

> [07:40:40 UTC 2018/08/07] [CRIT] (mongoshake/executor.(*Executor).execute:108) Replayer-2, executor-2, oplog for [dev.users] op[u] failed. (*errors.errorString) [doUpdate run upsert/update[true] failed[The $v update field is only recognized internally]], logs 1. firstLog &{6575777281602486273 u dev.users map[$v:1 $set:map[lastname:Zamir]] map[_id:ObjectIdHex("5b41d9f9e35d435d6f507f94")] map[] map[] 0 0}

After a little bit of search online, I found https://jira.mongodb.org/browse/SERVER-32240 , If I understood it, the error occurs because they added the $v field in the oplog on the 3.6 version.

**Comment by omrishtam** [comment]
Same issue here
I'm stuck because of it, it's very important!

**Comment by galshiff** [comment]
I having the same problem...
It seems to be the problem @omerzamir describes above.

**Comment by LiorHaim** [comment]
Same here.

**Comment by vinllen** [comment]
@omerzamir What MongoDB version do you use on the target side? So you guys try to sync data from mongo-3.6 to mongo-3.4, right?

**Comment by omerzamir** [comment]
@vinllen I am trying to sync data from mongo 3.6 to mongo 3.6.
Same version at target and destination...

**Comment by y123456yz** [comment]
+1

**Comment by vinllen** [comment]
This is because of mongo-3.6 add internal $v filed which can't be recognized in mgo.v2 library, we will fix it soon.

**Comment by vinllen** [comment]
Please check out `bugfix-1.2.1` branch and do the test, let me know if problem solved.
Current solution: remove "$v" internal field in the "o" field in the update operation if exist. This field looks very strange and no better solution came into my mind. Maybe mongo stream can erase this field, I'll check it later.

**Comment by omerzamir** [comment]
It's seems to solve the issue and it's working fine now.
Thank you!
