### ISSUE TITLE
docs/rpc

### ISSUE THREAD

**Issue by whrrmydragons** [aliyun/mongo-shake#29]
Im trying to use mongoshake with rpc if you could provide some examples in the documentation on how to do that?
also if you could provide some examples for ETL flows using mongoshake?

**Comment by vinllen** [comment]
@whrrmydragons  v1.4.0 version is released, plz see the FAQ document to see more details.

**Comment by vinllen** [comment]
please reopen this question to let me know if you still not clear about tunnel connection.
