### ISSUE TITLE
check point doesn't update，and it causes OOM

### ISSUE THREAD

**Issue by xiaotianxing** [aliyun/mongo-shake#30]
I use tunnel file，and find the document in ckpt_default doesn't update。the process will continue to consume memory，until OOM。
the ckpt_default document is：
{ "_id" : ObjectId("5b7a3b1dd001499fc4c2359e"), "name" : "rs2", "ckpt" : Timestamp(946656001, 0) }

**Comment by vinllen** [comment]
Could you show the configuration and your OOM limit threshold?

**Comment by xiaotianxing** [comment]
how much memory will be used by mongo-shake? I find it will consume too much memory。

**Comment by vinllen** [comment]
Generally speaking, mongoshake will at most use 500MB memory based on the default configuration. Please contact me in the WeChat group, I'll help you to find the problem

**Comment by xiaotianxing** [comment]
好的，我刚才应该已经加您微信了，BruceM（马凯君）

**Comment by vinllen** [comment]
So this problem can be closed. Please reopen it if anyone has the same problem.
