### ISSUE TITLE
Mongoshake with Kafka

### ISSUE THREAD

**Issue by Baraks24** [aliyun/mongo-shake#32]
Hello,
I get the following error after trying to use MongoShake with Kafka : "Oplog Tailer initialize failed: worker initialize error". It only occurs with Kafka, when using other tunnel pipeline types like direct/File/RPC this error is not shown. I have a MongoDB replica set of 3 members (1 primary, 2 secondaries) and one Kafka broker with "mongoshake" topic in it.
mongo_urls is of the form : mongodb://IP_ADDR1:27017,IP_ADDR2:27017,IP_ADDR3:27017
and tunnel.address is of the form mongoshake@BROKER_IP and tunnel is set to kafka.
Does someone have an idea of how to solve this problem?
Thanks

**Comment by vinllen** [comment]
Could you show me your configuration and error log? Here comes the example for Kafka tunnel:
`
tunnel = kafka
tunnel.address = mongoshake@127.0.0.1:9092

context.storage = database
context.storage.url = mongodb://127.0.0.1:20080
context.address = ckpt
context.start_position = 2000-01-01T00:00:01Z
`

**Comment by vinllen** [comment]
please reopen it if you still have same problem
