### ISSUE TITLE
Skip error

### ISSUE THREAD

**Issue by Ars3nik** [aliyun/mongo-shake#40]
Hi,

I got an error like 

`[10:14:51 CEST 2018/09/06] [CRIT] (mongoshake/executor.(*Executor).execute:108) Replayer-1, executor-1, oplog for [DB.coll] op[u] failed. (*errors.errorString) [doUpdate run upsert/update[true] failed[cannot use the part (3 of h.3.odt) to traverse the element ({3: null})]], logs 64. firstLog &{6597668025535561848 u  DB.coll map[$set:map[h.672.odt:2018-09-05 08:27:51 +0000 UTC h.672.oct:1]] map[_id:ObjectIdHex("594fb8ffa4efa290145b4c18")] map[] map[] 0 0}
`
and it loop over it, is there a way to skip on error ?

Thanks in advance.

**Comment by vinllen** [comment]
Currently, MongoShake only ignores the known error. If you want to skip all errors, you should modify the error judge code by yourself.

**Comment by vinllen** [comment]
checkout this [question](https://stackoverflow.com/questions/39088123/mongodb-cannot-use-the-part-to-traverse-the-element-undefined), I think the filed 3 already exists.

**Comment by Ars3nik** [comment]
What is strange is that when I replay that particular entry in the oplog manualy the result is a success. But MongoShake raise an error. I can't explain that, you never have that kind of error ?

**Comment by vinllen** [comment]
Do you use `upsert`?

**Comment by vinllen** [comment]
I'll add skipping all error switch in the configuration which will be released in the next two days.

**Comment by Ars3nik** [comment]
My Config is : 

replayer.dml_only = true
replayer.executor = 1
replayer.executor.upsert = true
replayer.executor.insert_on_dup_update = false
replayer.conflict_write_to = none
replayer.durable = true

Yes I use upsert, that's why I don't understand why manually it works and thru mongoshake it raise an error ..

**Comment by Ars3nik** [comment]
MongoDB version v3.4.10
MongoDB shell version v3.4.10

**Comment by vinllen** [comment]
The source database version is also 3.4? Could you give me the error oplog? And how do you manually insert the oplog?

**Comment by Ars3nik** [comment]
This error has gone, I'm running it for 2 days since error ..

**Comment by Ars3nik** [comment]
I got another question, why sometime it seem to "freeze" with 0 logs_get/sec  for several minutes .. and the lsn.time is mote than hour ahead from the  lsn_ckpt.time. It's normal to be ahead but more than une hour ? How can I optimize that ?

**Comment by vinllen** [comment]
please reopen this issue if your problem still exists.
