### ISSUE TITLE
mongoshake context storage with api

### ISSUE THREAD

**Issue by iamyangjy** [aliyun/mongo-shake#41]
collector context storage mainly including store checkpoint
type include : database, api
for api storage, address is http url
看配置文件中，mongoshake上下文信息保存方式可以为api。对于api的接口如何定义，能否举个例子说明下

**Comment by vinllen** [comment]
api比如可以提供存储的http/restful接口，支持kv的Post存储时间戳和Get获取时间戳，如果api有不同的对接方式，可以修改api代码中的对接方式

**Comment by iamyangjy** [comment]
OK。到时看下源码。
