### ISSUE TITLE
多个数据库配置同步方案

### ISSUE THREAD

**Issue by zhaojunlike** [aliyun/mongo-shake#5]
您好，请问有没有完善点的资料和文档，目前我有一个多个mongodb的备份需求，目的是做一套线下的数据库同步线上数据的方案，线下数据不会影响线上的数据，线上数据拉下来如果遇到本地冲突就抛弃，我看你们的项目有这个功能，所以非常兴奋，我们之前也是通过oplog同步，但是库太多表太多一直没找到一个好的同步方案，麻烦您们能有一份配置文档

**Comment by zhaojunlike** [comment]
尼外我们也使用了4套aliyun mongodb，我们之前是没有看到oplog中携带的有uk参数，版本是3.4 3.2 请问需要配置什么吗？

**Comment by vinllen** [comment]
对于第一个问题，你说的是最基本的mongoshake拉取功能，源对接线上，目的对接线下，正常配置就可以，冲突是否抛弃这个也可以配置。
第二个问题，这个字段目前还未加入，有部分性能上的影响，但是功能上是正常的。
