### ISSUE TITLE
关于MongoShake应靠近目标还是源的问题

### ISSUE THREAD

**Issue by shiftyman** [aliyun/mongo-shake#54]
FAQ中提到，想要提高QPS，尽量将MongoShake靠近目标。

但是，我觉得oplog的网络传输可能才是瓶颈。MongoShake用了比如并行复制，发送前压缩，操作merge，无关oplog过滤等这些优化手段，理论上应该能在对oplog在传输到tunnel之前做一定的压缩。所以如果将MongoShake靠近源（比如同机房），最终网络上传输的数据就会变得更少，所以也有可能靠近源性能更好不是吗？

求解答，谢谢

**Comment by vinllen** [comment]
如果是非direct模式，那么肯定是靠近源比较方便，通过tunnel进行传输。如果是direct模式，oplog的拉取速率远大于写入速率，且写入需要多次报文交互，网络会成为瓶颈，所以靠近目的端解决写入速率问题提高整体qps。
