### ISSUE TITLE
分片集群同步，checkpoint持久化失败问题

### ISSUE THREAD

**Issue by shiftyman** [aliyun/mongo-shake#60]
shading集群，关键配置如下：

context.storage = database
context.storage.url = mongodb://127.0.0.1:20070（配置的是源的mongos，是不是这个配置有问题？？）
context.address = ckpt_default

日志有如下信息：

[2018/10/09 20:35:19 CST] [WARN] [collector.(*OplogSyncer).checkpoint:64] CheckpointOperation updated is not suitable. lowest [0]. current [406598025991
5268096]. reason : no candidates ack values found

**Comment by vinllen** [comment]
这个log并不是checkpoint持久化失败，运行一段时间后（默认好像是3分钟）会写入

**Comment by shiftyman** [comment]
貌似如果没有任何同步的历史，会一致输出这个日志，并且不记录checkpoint，当同步一条之后就好了，记录checkpoint且日志消失。

**Comment by vinllen** [comment]
是，没有数据同步不会写入checkpoint
