### ISSUE TITLE
MongoShake的使用问题

### ISSUE THREAD

**Issue by EvenGui** [aliyun/mongo-shake#66]
1. mongoshake重启后，能否做到采集oplog的数据不丢失，不重复？是如何做到的？

2.mongoshake的HA方案，未来是否可以考虑利用像zookeeper这种服务，部署成集群模式的HA，一台机器active状态，另外一台机器为standby状态。active机器挂了。standby转换成active。持续读oplog

3.对于kafka，file，tcp，rpc，这几种消费数据的操作，是否可以独立出来。server只需要读取oplog，由用户编写client，来消费server发布的消息，这种方式可能对数据的消费，处理的更灵活一些。

4.目前数据发kafka，是单topic单分区，来保证数据的有序消费。是否可以支持多分区发送消息。（例如同一表发送相同的分区，也能做到数据库的单表有序消费）。

5.目前写入数据是采用go语言的binary.Write，Java如何解析从kafka，tcp，rpc发送的数据。

**Comment by vinllen** [comment]
1. checkpoint机制，写入成功更新checkpoint，挂掉重启后从之前的checkpoint开始读取，保证数据不丢失；对于dml来说，满足幂等率，重复无所谓
2. mongoshake有HA机制，详细请查看配置文件`master_quorum `字段
3. 现在已经独立，用户client可以进行自己消费，不过问题是组织的二进制数据解析不好处理，而且有压缩等机制在里面，用户可以用receiver进行对接，帮助处理了解压缩等逻辑，对接后吐给用户client
4. 目前不行
5. 参考3

**Comment by vinllen** [comment]
please reopen it if you still have the same questiones
