### ISSUE TITLE
源库是mongos

### ISSUE THREAD

**Issue by zengjiancang** [aliyun/mongo-shake#69]
# connect source mongodb, set username and password if enable authority.
# split by comma(,) if use multiple instance in one replica-set.
# split by semicolon(;) if sharding enable.
mongo_urls = mongodb://username:password@127.0.0.1:20040,127.0.0.1:20041

这个参数表示可以源库配置为mongos，但是我自己配置源库是mongos，使用direct的方式，会报错在源库找不到mongos，请问是direct方式不支持源库是mongos吗？

**Comment by vinllen** [comment]
sharding请从shard分片进行oplog拉取
