### ISSUE TITLE
分片集群+唯一索引的场景 是否能正确处理？

### ISSUE THREAD

**Issue by shiftyman** [aliyun/mongo-shake#71]
当集合分片了，比如col集合，数据分布在shard1，和shard2上，col集合的键key建立了唯一索引且key不是sharding-key，此时，mongoshake以集合维度进行并发处理。

问题来了：
首先，shard1上的col集合部分，先执行：insert key=1，后执行 update key = 2；
然后，shard2上的col集合部分，执行：insert key=1
这个执行时可以进行的，因为shard2 insert之前，shard1已经将key update了。

但是，由于没有全局时序，假设 shake首先拉取到shard1点insert语句，然后拉取到shard2点insert语句，再取到shard1点update语句，那么岂不是shard2的insert会失败？

这个问题，shake如何处理？还是会有问题呢？

**Comment by gugemichael** [comment]
@shiftyman 你好，描述中“键key”是唯一索引，单不是shardkey，不知道我这样理解对不对 ？这种在mongo理是不允许的。

**Comment by shiftyman** [comment]
谢谢，是我多虑了
