### ISSUE TITLE
多线程持续insert，shake程序挂掉？？？

### ISSUE THREAD

**Issue by shiftyman** [aliyun/mongo-shake#74]
多线程做压测，只有insert语句，跑着跑着就这样了？什么情况？

goroutine 209 [sleep]:
time.Sleep(0x37e11d600)
        /home/peng/go/go/src/runtime/time.go:105 +0x14f
vendor/github.com/vinllen/mgo.(*mongoServer).pinger(0xc0002432c0, 0xc0081c2a01)
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/server.go:407 +0x4a1
created by vendor/github.com/vinllen/mgo.newServer
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/server.go:107 +0x156

goroutine 173 [select]:
vendor/github.com/vinllen/mgo.(*mongoCluster).syncServersLoop(0xc006b5e5a0)
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/cluster.go:431 +0x2f0
created by vendor/github.com/vinllen/mgo.newCluster
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/cluster.go:83 +0x17d

goroutine 175 [sleep]:
time.Sleep(0x37e11d600)
        /home/peng/go/go/src/runtime/time.go:105 +0x14f
vendor/github.com/vinllen/mgo.(*mongoServer).pinger(0xc0001eeff0, 0xc0050e1601)
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/server.go:407 +0x4a1
created by vendor/github.com/vinllen/mgo.newServer
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/server.go:107 +0x156

goroutine 188 [IO wait]:
internal/poll.runtime_pollWait(0x7fdf64675480, 0x72, 0xc000283c98)
        /home/peng/go/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00012cf98, 0x72, 0xffffffffffffff00, 0xa5f4a0, 0xdb1698)
        /home/peng/go/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00012cf98, 0xc006b89000, 0x10, 0x10)
        /home/peng/go/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00012cf80, 0xc006b89030, 0x10, 0x10, 0x0, 0x0, 0x0)
        /home/peng/go/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc00012cf80, 0xc006b89030, 0x10, 0x10, 0xc00012cf80, 0x0, 0x0)
        /home/peng/go/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0001f60f8, 0xc006b89030, 0x10, 0x10, 0x0, 0x0, 0x0)
        /home/peng/go/go/src/net/net.go:177 +0x68
vendor/github.com/vinllen/mgo.fill(0xa65940, 0xc0001f60f8, 0xc006b89030, 0x10, 0x10, 0x0, 0x91)
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/socket.go:601 +0x53
vendor/github.com/vinllen/mgo.(*mongoSocket).readLoop(0xc005262900)
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/socket.go:619 +0x122
created by vendor/github.com/vinllen/mgo.newSocket
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/socket.go:211 +0x1df

goroutine 227 [select]:
vendor/github.com/vinllen/mgo.(*mongoCluster).syncServersLoop(0xc0082ff0e0)
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/cluster.go:431 +0x2f0
created by vendor/github.com/vinllen/mgo.newCluster
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/cluster.go:83 +0x17d

goroutine 189 [IO wait]:
internal/poll.runtime_pollWait(0x7fdf646753b0, 0x72, 0xc005942c98)
        /home/peng/go/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000160898, 0x72, 0xffffffffffffff00, 0xa5f4a0, 0xdb1698)
        /home/peng/go/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000160898, 0xc006b89200, 0x10, 0x10)
        /home/peng/go/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000160880, 0xc006b89290, 0x10, 0x10, 0x0, 0x0, 0x0)
        /home/peng/go/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000160880, 0xc006b89290, 0x10, 0x10, 0xc000160880, 0x0, 0x0)
        /home/peng/go/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0001f6108, 0xc006b89290, 0x10, 0x10, 0x0, 0x0, 0x0)
        /home/peng/go/go/src/net/net.go:177 +0x68
vendor/github.com/vinllen/mgo.fill(0xa65940, 0xc0001f6108, 0xc006b89290, 0x10, 0x10, 0x0, 0x91)
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/socket.go:601 +0x53
vendor/github.com/vinllen/mgo.(*mongoSocket).readLoop(0xc005262d80)
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/socket.go:619 +0x122
created by vendor/github.com/vinllen/mgo.newSocket
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/socket.go:211 +0x1df

goroutine 229 [sleep]:
time.Sleep(0x37e11d600)
        /home/peng/go/go/src/runtime/time.go:105 +0x14f
vendor/github.com/vinllen/mgo.(*mongoServer).pinger(0xc000243680, 0xc0081c2a01)
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/server.go:407 +0x4a1
created by vendor/github.com/vinllen/mgo.newServer
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/server.go:107 +0x156

goroutine 177 [IO wait]:
internal/poll.runtime_pollWait(0x7fdf646752e0, 0x72, 0xc00027ec98)
        /home/peng/go/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00012d118, 0x72, 0xffffffffffffff00, 0xa5f4a0, 0xdb1698)
        /home/peng/go/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00012d118, 0xc005718200, 0x10, 0x10)
        /home/peng/go/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00012d100, 0xc005718200, 0x10, 0x10, 0x0, 0x0, 0x0)
        /home/peng/go/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc00012d100, 0xc005718200, 0x10, 0x10, 0xc00012d100, 0x0, 0x0)
        /home/peng/go/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0001280a0, 0xc005718200, 0x10, 0x10, 0x0, 0x0, 0x0)
        /home/peng/go/go/src/net/net.go:177 +0x68
vendor/github.com/vinllen/mgo.fill(0xa65940, 0xc0001280a0, 0xc005718200, 0x10, 0x10, 0x0, 0x91)
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/socket.go:601 +0x53
vendor/github.com/vinllen/mgo.(*mongoSocket).readLoop(0xc006fa2000)
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/socket.go:619 +0x122
created by vendor/github.com/vinllen/mgo.newSocket
        /home/peng/gopath/src/mongo-shake/src/vendor/github.com/vinllen/mgo/socket.go:211 +0x1df

**Comment by vinllen** [comment]
看起来像是mgo驱动的bug，具体原因看不出来，描述一下使用的数据库版本，mongoshake版本等基本信息

**Comment by vinllen** [comment]
这个是全量core的日志信息？core的时候还有别的信息吗
