### ISSUE TITLE
分片集群同步配置该怎么填写？

### ISSUE THREAD

**Issue by ipcpu** [aliyun/mongo-shake#76]
比如我三台机器上都运行了mongos，3个分片的mongod（shard1，shard2，shard3）和1个configserver，如下
>mongos是192.168.1.1:27021,192.168.1.2:27021,192.168.1.3:27021
>configserver是192.168.1.1:27020,192.168.1.2:27020,192.168.1.3:27020
>shard1是192.168.1.1:27017,192.168.1.2:27017,192.168.1.3:27017
>shard2是192.168.1.1:27018,192.168.1.2:27018,192.168.1.3:27018
>shard3是192.168.1.1:27019,192.168.1.2:27019,192.168.1.3:27019
我的目的端和源端一样的配置，IP地址是4,5,6，配置文件该怎么填写？

```
#源
mongo_urls = mongodb://192.168.1.1:27017,192.168.1.1:27018,192.168.1.1:27019

#context
context.storage = database
context.storage.url = mongodb://127.0.0.1:27017
context.address = ckpt_default

#目的
tunnel = direct
tunnel.address = mongodb://192.168.1.4:27017,192.168.1.4:27018,192.168.1.4:27019
```
除了这些，configserver是不是也需要建立一个同步通道？

**Comment by vinllen** [comment]
shake不对config server进行同步
