### ISSUE TITLE
关于其他管道传输

### ISSUE THREAD

**Issue by glowwormX** [aliyun/mongo-shake#78]
我在FAQ document中看过了有关问题，使用file方式在本地测试中receiver已经成功收到oplog，但是不知道如何再写到数据库中，刚接触golang，能否给一个示例

**Comment by vinllen** [comment]
除direct通道外的通道都是只提供拉取通道，后续处理是用户自己实现的，比如是再发送到别的平台，还是自己写入数据库。
关于写入数据库的逻辑处理可以看看源码，代码应该在db_writer.go

**Comment by vinllen** [comment]
mongoshake双向同步是不能依赖于gid的，gid部分是数据库层面的修改，而不是通道层面，mongodb的开源公司目前还没有进入排期。

**Comment by glowwormX** [comment]
没有gid或者其他标识会进入环形复制，通过通道层面能避免这个问题么，除此之外mongoshake做双向同步的话还会有什么问题么

**Comment by vinllen** [comment]
看看faq中给出的多活方案，通过过滤可以实现。

**Comment by glowwormX** [comment]
好的谢谢
