### ISSUE TITLE
release-v1.0.0-20180718 编译后，使用默认配置，运行报错

### ISSUE THREAD

**Issue by iamyangjy** [aliyun/mongo-shake#8]
release-v1.0.0-20180718 编译后，使用默认配置，运行报错，错误日志如下
[11:19:47 CST 2018/07/19] [CRIT] (mongoshake/executor.(*Executor).execute:107) Replayer-0, executor-0, oplog for [db008.test01] op[i] failed. (*errors.errorString) [EOF], logs 1. firstLog &{6579760464337567746 i  db008.test01 map[_id:ObjectIdHex("5b50014081ab277c676f2f61") name:canyou ok] map[] map[] map[] 0 0}

**Comment by vinllen** [comment]
贴一下Mongodb的版本，还有出错的这条Oplog具体内容能够给出吗？_id=5b50014081ab277c676f2f61

**Comment by iamyangjy** [comment]
编译go版本 1.10.3， mongodb版本3.0.7
{ "_id" : ObjectId("5b50014081ab277c676f2f61"), "name" : "canyou ok" }

**Comment by iamyangjy** [comment]
使用这个版本可以。
commit ed14c5518e8afa097c3024306a55d58ab3338fe1
Author: vinllen <cvinllen@gmail.com>
Date:   Mon Jul 9 11:09:08 2018 +0800
    mofidy configuration
配置如下
# oplog changes to Insert while Update found non-exist (_id or unique-index)
replayer.executor.upsert = true
# oplog changes to Update while Insert found duplicated key (_id or unique-index)
replayer.executor.insert_on_dup_update = false

**Comment by vinllen** [comment]
这个原因是3.0版本的mongodb不支持runCommand写入，在最新合入的代码中我们采用了runCommand写入的方式

**Comment by iamyangjy** [comment]
那是否能兼容下3.0的版本呢？

**Comment by vinllen** [comment]
建议升级mongodb到3.2版本以上进行操作。如果非要3.0版本，我评估一下，考虑进行兼容。这两天可能没时间搞了，计划周末或者下周一排期一下。

**Comment by iamyangjy** [comment]
目前生产环境都是用3.0的，短期内是没法做升级。希望能够在代码层面做下兼容，谢谢

**Comment by iamyangjy** [comment]
兼容mongo 3.0版本有排期吗？

**Comment by vinllen** [comment]
计划7月底之前

**Comment by vinllen** [comment]
@iamyangjy 你有3.0版本的具有公网ip的测试mongodb吗？目前3.0版本都下载不到了

**Comment by y123456yz** [comment]
@vinllen  3.x版本是否已支持

**Comment by vinllen** [comment]
此版本已修复，问题我先close了，如果测试发现有问题可以reopen进行反馈。
