### ISSUE TITLE
BSONObj size:is invalid.

### ISSUE THREAD

**Issue by fanlifei** [aliyun/mongo-shake#90]
(*mgo.BulkError) [BSONObj size: 21725988 (0x14B8324) is invalid. Size must be between 0 and 16793600(16MB)

**Comment by vinllen** [comment]
so this single oplog size is about 20MB?

**Comment by fanlifei** [comment]
> so this single oplog size is about 20MB?

源
configured oplog size:   307200MB
目的：
configured oplog size:   51200MB

**Comment by fanlifei** [comment]
> so this single oplog size is about 20MB?

源是副本集：
configured oplog size: 307200MB
目的是shrding:
configured oplog size: 51200MB

**Comment by vinllen** [comment]
这个报错的意思应该是单条oplog的大小到达了20MB，目前的写入上限是16MB，你确认一下是否有这种超大oplog

**Comment by vinllen** [comment]
有查看最大文档大小的命令，网上搜下吧
