### ISSUE TITLE
Oplog Tailer initialize failed: no oplog ns in mongo

### ISSUE THREAD

**Issue by supersujj** [aliyun/mongo-shake#92]
when use sharding sync,
conf urls:
mongo_urls = mongodb://sync:password@192.168.123.10:27021;192.168.123.20:27022;192.168.123.30:27023

but when exec:
./bin/collector -conf=conf/collector.conf

it issue :
[17:15:37 HKT 2018/12/18] [CRIT] (mongoshake/collector.(*ReplicationCoordinator).sanitizeMongoDB:67) There has no oplog collection in mongo db server
Oplog Tailer initialize failed: no oplog ns in mongo

what is happen?

**Comment by vinllen** [comment]
the source in your configuration is mongos ? If not, check the `local.oplog.rs` collection in your database.

**Comment by supersujj** [comment]
yes,my env is:
shard1 master: 192.168.123.10:27021
shard2 master: 192.168.123.20:27022
shard3 master: 192.168.123.30:27023

and when i connetc it use mongo shell,i can see the local.oplog.rs

shard1_zxl:PRIMARY> use local;
switched to db local
shard1_zxl:PRIMARY> show tables;
me
oplog.rs
replset.election
replset.minvalid
startup_log
system.replset

**Comment by vinllen** [comment]
any progress?

**Comment by supersujj** [comment]
i am sorry,i reply late,i want to say is:
i use is not mongos connect,i connect is sharding master
 shard1 master: 192.168.123.10:27021
shard2 master: 192.168.123.20:27022
shard3 master: 192.168.123.30:27023
config file is
mongo_urls = mongodb://sync:password@192.168.123.10:27021;192.168.123.20:27022;192.168.123.30:27023

**Comment by vinllen** [comment]
So each shard have local.oplog.rs inside?

**Comment by supersujj** [comment]
yes

**Comment by supersujj** [comment]
if i use mongo_urls = mongodb://sync:password@192.168.123.10:27021
it can sync normal

**Comment by supersujj** [comment]
i use one sharding master,the log will issuse:
[EEROR] [collector.(*OplogSyncer).next:259] oplog collection capped error, users should fix it manually

**Comment by vinllen** [comment]
please check out "collection capped error" question in faq

**Comment by supersujj** [comment]
what is the problem i use sharding url:
mongo_urls = mongodb://sync:password@192.168.123.10:27021;192.168.123.20:27022;192.168.123.30:27023 ?

**Comment by vinllen** [comment]
You can follow this source code `(mongoshake/collector.(*ReplicationCoordinator).sanitizeMongoDB:67)` to debug.

**Comment by supersujj** [comment]
how to do?

**Comment by vinllen** [comment]
please reopen this issue if anyone has the same question

**Comment by SunnySoulLon** [comment]
> please reopen this issue if anyone has the same question

[2020/08/27 15:06:13 CST] [INFO] New session to mongodb://sync:***@dds-wz**********41.mongodb.rds.aliyuncs.com:3717 successfully
[2020/08/27 15:06:13 CST] [CRIT] There has no oplog collection in mongo db server

**Comment by vinllen** [comment]
checkout wiki faq

**Comment by SunnySoulLon** [comment]
源库是aliyun的mongodb复制集,  mongoshell 看是有的
mgset-33021339:PRIMARY> show tables
oplog.rs
replset.oplogTruncateAfterPoint

**Comment by vinllen** [comment]
看下wiki里面faq的说明，有问题请重开一个issue
