### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by jwillmer** [aliyun/mongo-shake#93]
Is there some tutorial how to setup, configure, etc? Your [`MongoShake Detailed Documentation`](https://github.com/aliyun/mongo-shake/wiki/MongoShake-Detailed-Documentation) only tells me what is possible but not how.

**Comment by vinllen** [comment]
Currently, we don't have the tutorial. You can check out the [usage](https://github.com/aliyun/mongo-shake#usage) to start MongoShake, if you want to set up with detail information, read the [comment of configuration](https://github.com/aliyun/mongo-shake/blob/master/conf/collector.conf) and the [wiki faq](https://github.com/aliyun/mongo-shake/wiki/FAQ)

**Comment by jwillmer** [comment]
O.K. when I have a few questions about it:

- How do I run the packages file one `mongo-shake/src/vendor`?
- Is there also a script to install govendor and is it correct to set the path to (`GOPATH=pwd/../..;`)?
- Is there an example config for a two way sync of mongodb between two instances? I looking at the two config files and I'm having a hard time figuring out which options I need to modify.

**Comment by vinllen** [comment]
Please be careful if you want build two-way sync tunnel, the data may be moved from the source to the target, and then from the target to the source.
Check out this question(How to build active-active replication(双活) in the current opensource version without gid support?) in the [faq](https://github.com/aliyun/mongo-shake/wiki/FAQ) to break the loop.

**Comment by jwillmer** [comment]
I read the [How to build active-active replication](https://github.com/aliyun/mongo-shake/wiki/FAQ#q-how-to-build-active-active-replication%E5%8F%8C%E6%B4%BB-in-the-current-opensource-version-without-gid-support) in the FAQ but it sounds like that active-active is not supported since I need to define a one way sync on collection level. Or do I miss something?

**Comment by vinllen** [comment]
Yes, the granularity of two-way syncing is collection level, so that you should filter some database/collection on one side, and filter the other db/collections on the other side. 
It is because mongodb doesn't support [gid](https://github.com/aliyun/mongo-shake/wiki/MongoShake-Detailed-Documentation#35-gid), so it's the only way to prevent data replication from forming a loop.

**Comment by jwillmer** [comment]
So basically that means I can't keep a collection in sync if I make changes on both servers to this collection?

**Comment by vinllen** [comment]
yes

**Comment by jwillmer** [comment]
That's unfortunate. Then I need to look for another solution. Thank you for the clarification.

**Comment by mymmoonoa** [comment]
> That's unfortunate. Then I need to look for another solution. Thank you for the clarification.

Hi Jwillmer, Did you find solution for a two way sync of mongodb between two instances?

**Comment by jwillmer** [comment]
> > That's unfortunate. Then I need to look for another solution. Thank you for the clarification.
> 
> Hi Jwillmer, Did you find solution for a two way sync of mongodb between two instances?

We plan to build an app that connects to a remote instance, listens to the events and publishes them in the local instance. This gives us also the benefit to filter what we like to keep in sync.

**Comment by mymmoonoa** [comment]
> > > That's unfortunate. Then I need to look for another solution. Thank you for the clarification.
> > 
> > 
> > Hi Jwillmer, Did you find solution for a two way sync of mongodb between two instances?
> 
> We plan to build an app that connects to a remote instance, listens to the events and publishes them in the local instance. This gives us also the benefit to filter what we like to keep in sync.

So you are developing the sync app, right?

Have you checked https://github.com/yougov/mongo-connector, our team prefers to use mongo-connector, but I need to figure out the feasibility of these tools.  
I would appreciate it if you could give any advise.

**Comment by jwillmer** [comment]
> I would appreciate it if you could give any advise.

We have the development of the tool in the backlog. So far I can't help u with expertise. Depending on the prioritization I can answer your questions in a couple of weeks.

**Comment by mymmoonoa** [comment]
> > I would appreciate it if you could give any advise.
> 
> We have the development of the tool in the backlog. So far I can't help u with expertise. Depending on the prioritization I can answer your questions in a couple of weeks.

OK I got it. Thanks a lot.

**Comment by hiep1097** [comment]
hi @vinllen, I am start using MongoShake. can I have some question about lastest version release-v2.4.9-20200806:
1. Is this version support two-way sync tunnel without using GID? I have 2 replicaset clusters, each have 3 node: one primary and two secondary, and 2 MongoShake to sync data between them. I write data to one cluster in one time (active-standby) and I saw that MongoShake run properly. 
2. how to use mongoshake-stat to monitor? I using command: ./mongoshake-stat --port=9100, but failed with error: ValueError: No JSON object could be decoded. 
Thanks a lot.

**Comment by vinllen** [comment]
1. No. If you use MongoShake in two-way sync, the consistency can't be guaranteed.
2. 9100 port is only used when running incr-sync stage, so if your MongoShake is running full-sync stage, you should use 9101 port, however, mongoshake-stat doesn't support 9101. You can curl the 9101 port directly to get the monitor data by: `curl 127.0.0.1:9101`.

**Comment by hiep1097** [comment]
> 1. No. If you use MongoShake in two-way sync, the consistency can't be guaranteed.
> 2. 9100 port is only used when running incr-sync stage, so if your MongoShake is running full-sync stage, you should use 9101 port, however, mongoshake-stat doesn't support 9101. You can curl the 9101 port directly to get the monitor data by: `curl 127.0.0.1:9101`.

1. Note that I write data to only one cluster in one time, mean active-standby, not active-active. Assuming that I have 2 clusters A and B, mongoshake 1 replicates data from A to B and mongoshake 2 replicates data from B to A. I insert 10 document to A, then B has 10 document replicated from A by mongoshake 1, and no data replicated back from B to A by mongoshake 2. No infinite data replication loop occur as you mention in GID feature. So why consistency can't be guaranteed? Do I miss something? Please explain to me.

**Comment by vinllen** [comment]
You can't break the sync loop without GID supported. Checkout this scenario, I just update `{_id:1, a:1}` to `{_id:1, a:2}` and generate an oplog: `{o2:{_id:1}, o:{_id:1, a:2}}`, when this oplog sync from A to the B, the data with `{_id:1}` will be updated and generate another oplog: `{o2:{_id:1}, o:{_id:1, a:2}}`. So once this oplog synced back to A, the `{_id:1}` will be updated again even the result is not changed. So there will be a loop: A->B->A->B->... 
As a result, when you update `{_id:1}` again to `{_id:1, a:3}`, the result of `{_id:1}` on A and B will switch back and forth between `{a:2}` and `{a:3}`.

**Comment by vinllen** [comment]
Please open a new issue if anyone has a question, this issue should be frozen.
